name: PZU Cost Calculator
slug: pzu_cost
version: "2.3.0"
description: PZU OPCOM cost calculator

startup: application
boot: auto
host_network: true
arch:
  - amd64
hassio_api: true
homeassistant_api: true   # ⭐ ASTA LIPSEA ⭐

options:
  imported_sensor: ""
  exported_sensor: ""
  tariff_distribution: 0.15
  tariff_transport: 0.03
  tariff_system: 0.01
  tariff_cogeneration: 0.02
  vat: 0.19

schema:
  imported_sensor: str
  exported_sensor: str
  tariff_distribution: float
  tariff_transport: float
  tariff_system: float
  tariff_cogeneration: float
  vat: float
